// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
    routeModules: RouteModules
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/project/:id": {
    params: {
      "id": string;
    };
  };
};

type RouteFiles = {
  "root.tsx": {
    id: "root";
    page: "/" | "/project/:id";
  };
  "pages/Home.tsx": {
    id: "pages/Home";
    page: "/";
  };
  "pages/Project.tsx": {
    id: "pages/Project";
    page: "/project/:id";
  };
};

type RouteModules = {
  "root": typeof import("./src/app/root.tsx");
  "pages/Home": typeof import("./src/app/pages/Home.tsx");
  "pages/Project": typeof import("./src/app/pages/Project.tsx");
};